name: speedcam
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cuda=11.7.1
  - h5py=3.7.0
  - hdf5=1.12.2
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - numpy=1.24.1
  - opencv=4.6.0
  - pip=22.3.1
  - python=3.9.7
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - scipy=1.10.0
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - pip:
    - huggingface-hub==0.11.1
    - timm==0.6.12
    - tqdm==4.64.1
    - wandb==0.13.9
    - appdirs==1.4.4
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - click==8.1.6
    - colorama==0.4.6
    - contourpy==1.1.0
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - filelock==3.12.2
    - filterpy==1.4.5
    - fonttools==4.42.0
    - gitdb==4.0.10
    - GitPython==3.1.32
    - idna==3.4
    - imageio==2.31.1
    - Jinja2==3.1.2
    - kiwisolver==1.4.4
    - lazy_loader==0.3
    - MarkupSafe==2.1.3
    - matplotlib==3.7.2
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.25.2
    - onnx==1.14.0
    - packaging==23.1
    - pandas==2.0.3
    - pathtools==0.1.2
    - Pillow==10.0.0
    - protobuf==4.24.0
    - psutil==5.9.5
    - py-cpuinfo==9.0.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytorch-model-summary==0.1.2
    - pytz==2023.3
    - PyWavelets==1.4.1
    - PyYAML==6.0.1
    - requests==2.31.0
    - scikit-image
    - scipy==1.11.1
    - seaborn==0.12.2
    - sentry-sdk==1.29.2
    - setproctitle==1.3.2
    - six==1.16.0
    - smmap==5.0.0
    - sympy==1.12
    - tifffile==2023.8.12
    - tqdm
    - typing_extensions
    - tzdata
    - ultralytics
    - urllib3
    - wandb
    